version = 1

[[listing]]
tag = "scimantic-yaml-v1"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v1.yaml"
sha256 = "0952c483c3e10c1801ced1ac9fece2fab04327786a087276fa4ed5a05c4fe0f8"

[[listing]]
tag = "scimantic-yaml-v2"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v2.yaml"
sha256 = "59245569589ecd69843cb544d6f45f637417d632b442a756b3486873fc980784"

[[listing]]
tag = "scimantic-yaml-v3"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v3.yaml"
sha256 = "d0158f9b4722cd21633534c99e71e1b5e2fd159d514a918d17084d271b76fcc8"
