version = 1

[[listing]]
tag = "scimantic-yaml-v1"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v1.yaml"
sha256 = "0952c483c3e10c1801ced1ac9fece2fab04327786a087276fa4ed5a05c4fe0f8"

[[listing]]
tag = "scimantic-yaml-v2"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v2.yaml"
sha256 = "59245569589ecd69843cb544d6f45f637417d632b442a756b3486873fc980784"

[[listing]]
tag = "scimantic-yaml-v3"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v3.yaml"
sha256 = "d0158f9b4722cd21633534c99e71e1b5e2fd159d514a918d17084d271b76fcc8"

[[listing]]
tag = "scimantic-yaml-v4"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v4.yaml"
sha256 = "292486adb4859103737a0fde49318010c21ef8ecc9075e989dba47248add177c"

[[listing]]
tag = "scimantic-yaml-v5"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v5.yaml"
sha256 = "86e5846f41f76a9348feb187d31aeebc3ec8a527aa1b678589ce732aeee61227"

[[listing]]
tag = "scimantic-yaml-v6"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v6.yaml"
sha256 = "d3ff9264986db7fd8ef9407bdd18be09094c5760746a4f278d39cfe2190ab6e8"

[[listing]]
tag = "scimantic-yaml-v7"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v7.yaml"
sha256 = "4b7922da5e9855a1ff460d881ebe47acffcd014f5bd7a5e8d65101674a745574"

[[listing]]
tag = "scimantic-yaml-v8"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v8.yaml"
sha256 = "8f83a163e25932cd1510354a6959a14e18a002c2cde7a75e8ecab94a2fd70691"

[[listing]]
tag = "scimantic-yaml-v9"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v9.yaml"
sha256 = "9d40356d01c289c9b829aea3701a3c6a9a88376a1da4b632e2e9ad8d02fbdf6c"

[[listing]]
tag = "scimantic-yaml-v10"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v10.yaml"
sha256 = "260e15a5f44fd3f2dddbc33e37cfd8a233feb4526557dfba21b33fcb4815b6bf"

[[listing]]
tag = "scimantic-yaml-v11"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v11.yaml"
sha256 = "dd9bd80b48632e19ab3697698813af95a67f3e49d4875720a91c002f8dedc599"

[[listing]]
tag = "scimantic-yaml-v12"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v12.yaml"
sha256 = "a4ce81695ef915867b8224b3a0eee88bba0ba582061833560cb17ac3743aae29"

[[listing]]
tag = "scimantic-yaml-v13"
source = "../schema/scimantic.yaml"
frozen = "src/listings/scimantic-yaml-v13.yaml"
sha256 = "6ea09878a4f3c730df306fa5c28d8b4c26a3da5352764f455311217b20466325"
